services:
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports: [ "5433:5432" ]
    volumes:
      - pgdata_products:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo -d productsdb" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  order-db:
    image: postgres:15-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports: [ "5434:5432" ]
    volumes:
      - pgdata_orders:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo -d ordersdb" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports: [ "5435:5432" ]
    volumes:
      - pgdata_users:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U demo -d usersdb" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports: [ "4000:4000" ]
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: auth-service
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/usersdb
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo123
      SERVER_PORT: 8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - app-network

  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: product-service
    depends_on:
      product-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/productsdb
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo123
      SERVER_PORT: 8081
      AUTH_SERVICE_URL: http://auth-service:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - app-network

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: order-service
    depends_on:
      order-db:
        condition: service_healthy
#      product-service:
#        condition: service_started
      kafka:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/ordersdb
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo123
      SERVER_PORT: 8082
      PRODUCT_SERVICE_URL: http://product-service:8081
      AUTH_SERVICE_URL: http://auth-service:8080
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: [ "9090:9090" ]
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: [ "2181:2181" ]
    mem_limit: 512m
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
      - "9093:9093"
    container_name: kafka
    mem_limit: 1g
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,INTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_MIN_INSYNC_REPLICAS=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app-network

  akhq:
    image: tchiotludo/akhq:0.25.1
    container_name: akhq
    ports:
      - "8086:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                  bootstrap.servers: "kafka:9093"
              zookeeper:
                url: "zookeeper:2181"
      AKHQ_SECURITY_AUTHENTICATION: |
        users:
          admin:
            name: admin
            password: admin
            role: Admin
      AKHQ_SECURITY_AUTHORIZATION: |
        permissions:
          - resource: Topic
            permission: Read
          - resource: Topic
            permission: Write
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata_products:
  pgdata_orders:
  pgdata_users:
  kafka_data:
  zookeeper_data: