services:
  postgres:
    image: postgres:15-alpine
    container_name: pg-products
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports:
      - "5432:5432"
    volumes:
      - pgdata_products:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d productsdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    depends_on: [ postgres ]
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productsdb
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo123
    ports: [ "8080:8080" ]

volumes:
  pgdata_products:
