spring.application.name=order-service
server.port=8082
spring.profiles.active=dev


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# JPA/Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

 # URL du product-service
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}

# Feign
feign.client.config.default.connectTimeout=2000
feign.client.config.default.readTimeout=2000
feign.client.config.default.loggerLevel=BASIC


