spring.application.name=order-service
server.port=8082
spring.profiles.active=dev


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.cloud.openfeign.circuitbreaker.enabled=true


management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.service=order-service

# JPA/Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
jwt.secret= your-256-bit-secret-key-here-please-change-this
 # URL du product-service
product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}

# Feign
feign.client.config.default.connectTimeout=2000
feign.client.config.default.readTimeout=2000
feign.client.config.default.loggerLevel=FULL

# Retry : ne re-tente pas les 4xx (erreurs fonctionnelles)
resilience4j.retry.instances.product-service.max-attempts=3
resilience4j.retry.instances.product-service.wait-duration=200ms
resilience4j.retry.instances.product-service.retry-exceptions=feign.RetryableException,feign.FeignException$ServiceUnavailable
resilience4j.retry.instances.product-service.ignore-exceptions=feign.FeignException$BadRequest,feign.FeignException$NotFound

# Circuit breaker
resilience4j.circuitbreaker.instances.product-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.product-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.product-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.product-service.wait-duration-in-open-state=15s
resilience4j.circuitbreaker.instances.product-service.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.product-service.automatic-transition-from-open-to-half-open-enabled=true

logging.level.org.springframework.security=INFO
logging.level.io.github.resilience4j=DEBUG
logging.level.com.demo.order.client=DEBUG
