# Profil local : bypass config-server, PostgreSQL local (docker-compose)
spring.config.import=
server.port=8082
# PostgreSQL local (docker-compose up order-db)
spring.datasource.url=jdbc:postgresql://localhost:5434/ordersdb
spring.datasource.username=${ORDER_DB_USER:demo}
spring.datasource.password=${ORDER_DB_PASSWORD:orderpass}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Security / Auth
security.auth.issuer=http://localhost:8080
security.auth.audience=ecommerce-api
security.permit-all=/actuator/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

# Kafka local (docker-compose up kafka)
spring.kafka.bootstrap-servers=localhost:9092
spring.cloud.openfeign.circuitbreaker.enabled=true
product-service.url=http://localhost:8081

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
