spring.application.name=product-service
springdoc.swagger-ui.path=/swagger-ui.html
spring.profiles.active=h2
KAFKA_BOOTSTRAP_SERVERS=localhost:9092

spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=*
management.metrics.tags.application=product-service
server.port=8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVICE_URL:http://localhost:8080}/.well-known/jwks.json
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO