spring.application.name=product-service
springdoc.swagger-ui.path=/swagger-ui.html
# Activer profil par défaut
spring.profiles.active=h2

# Hibernate : pas d'Open Session in View
spring.jpa.open-in-view=false